class DbSingletonDemo {
}

class DbSingleton {
 - {static} DbSingleton instance;
 - {static} Connection conn;
 - DbSingleton()
 + {static} getInstance()
 + getConnection()
}

DbSingletonDemo --> DbSingleton
