class CommandDemo {
}

class Light {
 - boolean isOn
 + toggle() 
 + on()
 + off()
}

class OnCommand {
 - Light light
 + execute()
}

class ToggleCommand {
 - Light light
 + execute()
}

class AllLightsCommand {
 - List<Light> lights
 + execute()
}

interface Command {
 + execute()
}

class Switch {
 + storeAndExecute(Command command)
}

CommandDemo --> Light
CommandDemo ..> OnCommand
CommandDemo ..> ToggleCommand
CommandDemo ..> AllLightsCommand

Light --> OnCommand
Light --> ToggleCommand
Light --> AllLightsCommand

Command <|-- OnCommand
Command <|-- ToggleCommand
Command <|-- AllLightsCommand

Switch o--> Command 
