class CommandDemo {
}

class Light {
 - boolean isOn
 + toggle() 
 + on()
 + off()
}

class OnCommand {
 - Light light
 + execute()
}

class ToggleCommand {
 - Light light
 + execute()
}

interface Command {
 + execute()
}

class Switch {
 + storeAndExecute(Command command)
}

CommandDemo --> Light
CommandDemo ..> OnCommand
CommandDemo ..> ToggleCommand

Light --> OnCommand
Light --> ToggleCommand

Command <|-- OnCommand
Command <|-- ToggleCommand

Switch o--> Command 
