class Client {
}

abstract class Handler {
 + {abstract} handleRequest()
}

class ConcreteHandler1 {
 + handleRequest()
}

class ConcreteHandler2 {
 + handleRequest()
}

Client ..> Handler

Handler <|-- ConcreteHandler1
Handler <|-- ConcreteHandler2

Handler --o ConcreteHandler2

