class Client {
}

class Memento {
 - state
 + getState()
 + setState()
}

class Originator {
 - state
 + getMemento()
 + setMemento()
}

class Caretaker {
}

Client --> Caretaker

Caretaker o--> Memento

Memento <.. Originator
